! A JI Chromatic.scl
! Created using Scale Workshop 1.2
!
! https://sevish.com/scaleworkshop/?name=A%20JI%20Chromatic&data=16%2F15%0A9%2F8%0A6%2F5%0A5%2F4%0A4%2F3%0A45%2F32%0A3%2F2%0A8%2F5%0A5%2F3%0A9%2F5%0A15%2F8%0A2%2F1&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ
!
A JI Chromatic
 12
!
 16/15
 9/8
 6/5
 5/4
 4/3
 45/32
 3/2
 8/5
 5/3
 9/5
 15/8
 2/1
