! Just Phrygian.scl
! Created using Scale Workshop 1.2
!
! https://sevish.com/scaleworkshop/?name=Just%20Phrygian&data=27%2F25%0A6%2F5%0A4%2F3%0A3%2F2%0A8%2F5%0A9%2F5%0A2%2F1%0A&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ
!
Just Phrygian
 7
!
 27/25
 6/5
 4/3
 3/2
 8/5
 9/5
 2/1
